// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LineCollapseController from "./line_collapse_controller"
application.register("line-collapse", LineCollapseController)

import LoadStatisticsController from "./load_statistics_controller"
application.register("load-statistics", LoadStatisticsController)
