inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'bin/webpack*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'postgres-data/**/*'

Rails:
  Enabled: true

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/catalog_controller.rb'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 6

RSpec/NestedGroups:
  Max: 4
