inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 130

Metrics/AbcSize:
  Exclude:
    - 'app/resource_builders/dlme_json_resource_builder.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/catalog_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/resource_builders/dlme_json_resource_builder.rb'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 6

RSpec/DescribeClass:
  Exclude:
    - 'spec/import/*'
