dist: trusty
addons:
  chrome: stable

notifications:
  email: false

rvm:
  - 2.4.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - bin/rails db:test:prepare
  - bin/rails assets:precompile

sudo: false
language: ruby
cache: bundler

jdk: oraclejdk8
