dist: trusty
notifications:
  email: false

rvm:
  - 2.5.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_script:
  - bin/rails db:test:prepare

sudo: false
language: ruby
cache: bundler

jdk: oraclejdk8
