version: 2.1
executors:
  docker-publisher:
    environment:
      WEBAPP_IMAGE_NAME: suldlss/dlme
      WORKER_IMAGE_NAME: suldlss/dlme-worker
    docker:
    - image: cimg/base:stable

orbs:
  browser-tools: circleci/browser-tools@1.1

jobs:
  debug:
    docker: # NOT the default
      - image: cimg/python:3.7-browsers
    steps:
      - run:
          name: Update AWS ECS
          command: |
            pip install awscli
            mkdir ~/.aws
            echo -e "[dlme]\naws_access_key_id=$CIRCLE_ACCESS_KEY_ID\naws_secret_access_key=$CIRCLE_SECRET_KEY\n" > ~/.aws/credentials
            unset  AWS_SESSION_TOKEN
            temp_role=$(aws sts assume-role \
                  --role-session-name "DevelopersRole" \
                  --role-arn $DEV_ROLE_ARN \
                  --profile dlme)
            export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
            export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
            export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
            aws configure set region us-west-2
            aws configure set output json
            aws configure list # Show confirmation of config

workflows:
  version: 2

  test:
    jobs:
    - debug:
        filters:
          branches:
            ignore: main
