version: 2.1
executors:
  docker-publisher:
    environment:
      WEBAPP_IMAGE_NAME: suldlss/dlme
      WORKER_IMAGE_NAME: suldlss/dlme-worker
    docker:
    - image: cimg/base:stable

orbs:
  browser-tools: circleci/browser-tools@1.1
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  test:
    docker:
    - image: cimg/ruby:2.7.5-browsers
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        RAILS_ENV: test
        NOKOGIRI_USE_SYSTEM_LIBRARIES: true
        CC_TEST_REPORTER_ID: 0603d31c367f7e726e4db6e249d4b62025c768000d43b02259a65e8486812362
    - image: solr:7
      command: bin/solr -cloud -noprompt -f -p 8983
    steps:
    - browser-tools/install-browser-tools
    - checkout
    - run: |
        google-chrome --version
    # Upgrade bundler
    - run:
        name: Install Bundler
        command: gem install bundler

    # Which version of bundler?
    - run:
        name: Which bundler?
        command: bundle -v

    # Restore bundle cache
    - restore_cache:
        keys:
        - dlme-bundle-v3-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - dlme-bundle-v3-{{ arch }}-{{ .Branch }}
        - dlme-bundle-v3-

    - run:
        name: Bundle Install
        command: bundle check || bundle install

    - run: bundle clean --force

    # Store bundle cache
    - save_cache:
        key: dlme-bundle-v3-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle

    # Only necessary if app uses webpacker or yarn in some other way
    - restore_cache:
        keys:
          - dlme-yarn-{{ checksum "yarn.lock" }}
          - dlme-yarn-

    - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

    # Store yarn / webpacker cache
    - save_cache:
        key: dlme-yarn-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn

    - run:
        name: Test prepare
        command: bin/rails db:test:prepare

    # Create a Solr collection
    - run:
        name: Load config into SolrCloud
        command: |
          cd solr/config
          zip -1 -r solr_config.zip ./*
          curl -H "Content-type:application/octet-stream" --data-binary @solr_config.zip "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=dlme"
          curl -H 'Content-type: application/json' http://localhost:8983/api/collections/ -d '{create: {name: dlme, config: dlme, numShards: 1}}'

    - run:
        name: Check styles using rubocop
        command: bundle exec rubocop

    - run:
        name: Setup Code Climate test-reporter
        command: |
          # download test reporter as a static binary
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
          chmod +x ./tmp/cc-test-reporter

    # Run rspec in parallel
    - run:
        name: Run rspec in parallel
        command: |
          ./tmp/cc-test-reporter before-build
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
    - run:
        name: Code Climate Test Coverage
        command: |
          ./tmp/cc-test-reporter format-coverage -t simplecov -o "coverage/codeclimate.$CIRCLE_NODE_INDEX.json"
    - run:
        name: Upload coverage results to Code Climate
        command: |
          ./tmp/cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 1 -o coverage/codeclimate.total.json
          ./tmp/cc-test-reporter upload-coverage -i coverage/codeclimate.total.json

    # Save test results for timing analysis
    - store_test_results:
        path: test_results

  build-image:
    executor: docker-publisher
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
        version: 20.10.11
    - run:
        name: Build Docker image
        command: |
          docker build . -f docker/Dockerfile -t $WEBAPP_IMAGE_NAME:latest --build-arg SECRET_KEY_BASE=$MASTER_KEY
          docker build . -f docker/Dockerfile.worker -t $WORKER_IMAGE_NAME:latest

    - run:
        name: Archive Docker image
        command: |
          docker save -o webapp_image.tar $WEBAPP_IMAGE_NAME
          docker save -o worker_image.tar $WORKER_IMAGE_NAME

    - persist_to_workspace:
        root: .
        paths:
        - ./webapp_image.tar
        - ./worker_image.tar
  publish-latest:
    executor: docker-publisher
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - setup_remote_docker:
        version: 20.10.11
    - run:
        name: Load archived Docker image
        command: |
          docker load -i /tmp/workspace/webapp_image.tar
          docker load -i /tmp/workspace/worker_image.tar

    - run:
        name: Publish Docker Image to Docker Hub
        command: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker push $WEBAPP_IMAGE_NAME:latest
          docker push $WORKER_IMAGE_NAME:latest

  publish-tag:
    executor: docker-publisher
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - setup_remote_docker:
        version: 20.10.11
    - run:
        name: Load archived Docker image
        command: |
          docker load -i /tmp/workspace/webapp_image.tar
          docker load -i /tmp/workspace/worker_image.tar

    - run:
        name: Publish Docker Image to Docker Hub
        command: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker tag $WEBAPP_IMAGE_NAME:latest $WEBAPP_IMAGE_NAME:$CIRCLE_TAG
          docker tag $WEBAPP_IMAGE_NAME:latest $WEBAPP_IMAGE_NAME:release
          docker tag $WORKER_IMAGE_NAME:latest $WORKER_IMAGE_NAME:$CIRCLE_TAG
          docker tag $WORKER_IMAGE_NAME:latest $WORKER_IMAGE_NAME:release
          docker push $WEBAPP_IMAGE_NAME:$CIRCLE_TAG
          docker push $WEBAPP_IMAGE_NAME:release
          docker push $WORKER_IMAGE_NAME:$CIRCLE_TAG
          docker push $WORKER_IMAGE_NAME:release

  update_ecs_dev:
    executor:
      name: aws-cli/default
      python-version: '3.9-browsers'
    environment:
      DLME_DEPLOY_REGION: us-west-2
    steps:
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: CIRCLE_ACCESS_KEY_ID
          aws-secret-access-key: CIRCLE_SECRET_KEY
          aws-region: DLME_DEPLOY_REGION
          role-arn: DEV_ROLE_ARN
      - update_ecs:
          ecs_cluster_name: ":cluster/dlme-dev"

  update_ecs_uat:
    executor:
      name: aws-cli/default
      python-version: '3.9-browsers'
    environment:
      DLME_DEPLOY_REGION: us-west-2
    steps:
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: CIRCLE_ACCESS_KEY_ID
          aws-secret-access-key: CIRCLE_SECRET_KEY
          aws-region: DLME_DEPLOY_REGION
          role-arn: STAGE_ROLE_ARN
      - update_ecs:
          ecs_cluster_name: ":cluster/dlme-uat"

  update_ecs_stage:
    executor:
      name: aws-cli/default
      python-version: '3.9-browsers'
    environment:
      DLME_DEPLOY_REGION: us-west-2
    steps:
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: CIRCLE_ACCESS_KEY_ID
          aws-secret-access-key: CIRCLE_SECRET_KEY
          aws-region: DLME_DEPLOY_REGION
          role-arn: STAGE_ROLE_ARN
      - update_ecs:
          ecs_cluster_name: ":cluster/dlme"


  update_ecs_prod:
    executor:
      name: aws-cli/default
      python-version: '3.9-browsers'
    environment:
      DLME_DEPLOY_REGION: us-west-2
    steps:
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: CIRCLE_ACCESS_KEY_ID
          aws-secret-access-key: CIRCLE_SECRET_KEY
          aws-region: DLME_DEPLOY_REGION
          role-arn: PROD_ROLE_ARN
      - update_ecs:
          ecs_cluster_name: ":cluster/dlme"

  debug:
    executor:
      name: aws-cli/default
      python-version: '3.9-browsers'
    environment:
      DLME_DEPLOY_REGION: us-west-2
    steps:
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: CIRCLE_ACCESS_KEY_ID
          aws-secret-access-key: CIRCLE_SECRET_KEY
          aws-region: DLME_DEPLOY_REGION
          role-arn: DEV_ROLE_ARN
      - run: aws configure list
commands:
  update_ecs:
    description: "Trigger an ECS service update"
    parameters:
      ecs_cluster_name:
        type: string
      webapp_service:
        type: string
        default: spotlight
      worker_service:
        type: string
        default: dlme-worker
    steps:
      - run: |
          aws configure set output json
          aws configure list # Show confirmation of config

          # identify the cluster we want to update
          cluster_arn=$(aws ecs list-clusters | jq --raw-output --exit-status '.clusterArns[] | select(contains("<< parameters.ecs_cluster_name >>"))')

          # update the webapp
          task_arn=$(aws ecs list-task-definitions --family-prefix << parameters.webapp_service >> --sort DESC --max-items 1 | jq --raw-output --exit-status '.taskDefinitionArns[]')
          aws ecs update-service --service << parameters.webapp_service >> --cluster $cluster_arn --task-definition $task_arn --force-new-deployment

          # update the workers
          worker_task_arn=$(aws ecs list-task-definitions --family-prefix << parameters.worker_service >> --sort DESC --max-items 1 | jq --raw-output --exit-status '.taskDefinitionArns[]')
          aws ecs update-service --service << parameters.worker_service >> --cluster $cluster_arn --task-definition $worker_task_arn --force-new-deployment



workflows:
  version: 2

  test:
    jobs:
    - test:
        filters:
          branches:
            ignore: main
  build:
    jobs:
    - build-image:
        filters:
          branches:
            only: main
    - publish-latest:
        requires:
        - build-image
        filters:
          branches:
            only: main
    - update_ecs_dev:
        requires:
        - publish-latest
        filters:
          branches:
            only: main
    - update_ecs_uat:
        requires:
        - publish-latest
        filters:
          branches:
            only: main
  build-tags:
    jobs:
    - build-image:
        filters:
          tags:
            only: /^[0-9]+\.[0-9]+\.[0-9]+/
          branches:
            ignore: /.*/
    - publish-tag:
        requires:
        - build-image
        filters:
          tags:
            only: /^[0-9]+\.[0-9]+\.[0-9]+/
          branches:
            ignore: /.*/
    - update_ecs_stage:
        requires:
        - publish-tag
        filters:
          tags:
            only: /^[0-9]+\.[0-9]+\.[0-9]+/
          branches:
            ignore: /.*/
    - update_ecs_prod:
        requires:
        - publish-tag
        filters:
          tags:
            only: /^[0-9]+\.[0-9]+\.[0-9]+/
          branches:
            ignore: /.*/
