version: "3.6"

services:
  app:
    image: suldlss/dlme:latest
    depends_on:
      - postgres
    environment:
      REDIS_HOST: redis
      RDS_HOSTNAME: postgres
      RDS_DB_NAME: dlme
      RDS_USERNAME: postgres
      RDS_PASSWORD: dlme
      SOLR_URL: http://admin:admin@solr:8983/solr/dlme
      SECRET_KEY_BASE: dlme

  sidekiq:
    image: suldlss/dlme-worker:latest
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_HOST: redis
      RDS_HOSTNAME: postgres
      RDS_DB_NAME: dlme
      RDS_USERNAME: postgres
      RDS_PASSWORD: dlme
      SOLR_URL: http://admin:admin@solr:8983/solr/dlme
      SECRET_KEY_BASE: dlme

  postgres:
    image: postgres:10.17
    environment:
      POSTGRES_PASSWORD: dlme
      POSTGRES_DB: dlme

  solr:
    image: solr:8.11.1
    depends_on:
      - zookeeper
    environment:
      ZK_HOST: zookeeper:2181

  zookeeper:
    image: zookeeper:3.7.0
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok


  redis:
    image: "redis:5.0-alpine"
    command: redis-server
