version: "3.6"

services:
  app:
    image: suldlss/dlme:latest
    depends_on:
      - postgres
    environment:
      REDIS_HOST: redis
      RDS_HOSTNAME: postgres
      RDS_DB_NAME: dlme
      RDS_USERNAME: postgres
      RDS_PASSWORD: dlme
      SOLR_URL: http://admin:admin@solr:8983/solr/dlme
      SECRET_KEY_BASE: dlme

  sidekiq:
    image: suldlss/dlme-worker:latest
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_HOST: redis
      RDS_HOSTNAME: postgres
      RDS_DB_NAME: dlme
      RDS_USERNAME: postgres
      RDS_PASSWORD: dlme
      SOLR_URL: http://admin:admin@solr:8983/solr/dlme
      SECRET_KEY_BASE: dlme

  postgres:
    image: postgres:10.17
    environment:
      POSTGRES_PASSWORD: dlme
      POSTGRES_DB: dlme

  solr:
    image: bitnami/solr:8.11.1
    depends_on:
      - zookeeper
    environment:
      SOLR_CLOUD_BOOTSTRAP: "yes"
      SOLR_ENABLE_CLOUD_MODE: "yes"
      SOLR_ENABLE_AUTHENTICATION: "yes"
      SOLR_ADMIN_USERNAME: admin
      SOLR_ADMIN_PASSWORD: admin
      SOLR_ZK_HOSTS: zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      JVMFLAGS: -Dzookeeper.4lw.commands.whitelist=mntr,conf,ruok
      ZOO_SERVERS: zoo1:2888:3888

  redis:
    image: "redis:5.0-alpine"
    command: redis-server
