name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    strategy:
      matrix:
        ruby: ['3.0', '3.1']
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Ruby and dependencies
      uses: ruby/setup-ruby@v1.123.0
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Install JS dependencies
      run: yarn install --frozen-lockfile
    - name: Set up the database
      run: bin/rails db:test:prepare
    - name: Run CI rake task
      run: bin/rake ci
